### ISSUE TITLE
Flashing issue when a video is moved using setCoordinates() and used pause() and play().

### ISSUE THREAD

**Issue by uditgogoi** [maplibre/maplibre-gl-js#2922]
**maplibre-gl-js version**: 2.4

**browser**: chrome

Hello, I am new to using maplibre and mapbox JS sdk integration. I am trying to add video on the map in my Vue application. I have used mapbox and recently shifted to maplibre, but there's an issue which I am finding consistently in both the library. According to my use case, I need to move a video along the map based on the video timeline, i.e, as the video plays on, it moves on the map corresponding to the location shown in the video. I am doing that using setCoordinates() and for that I need to listen to event `sourcedata`. Since I can't update the coordinates at each `sourcedata` event call, I am using a setInterval method to update the video after each 2 sec. But as soon I pause the video and play it again, there has been a flashing issue coming up.

### Steps to Trigger Behavior

 1. Create a map using video. Using ```sourcedata``` event for a callback 
       ```map.value.on("sourcedata",()=> setIntervalId.value = setInterval(updateVideoCoords, 2000));```, I am updating the video coordinates in every time interval.
 2. Inside `updateVideoCoords()` function I am updating the video coordinates using  `setCoordinates()` function.
 3. On pausing and playing the video using `pause() `and `play()`, I am seeing a flashing effect

### Link to Demonstration
Here is a small [video](https://github.com/maplibre/maplibre-gl-js/assets/19547501/37a7088c-beb1-430d-8f30-2c2147ecdea0) on the issue I am facing.

### Expected Behavior

When I am pausing the video the video should be paused at the current location and when I am playing the video again, the video should be played from the current location without flashing issue.

### Actual Behavior
Currently, when I am playing the video again, the location and everything else is ok but the flashing issue comes up. This has been consistent in both maplibre and mapbox library.

Please do help me out on this issue, as I've spent quite sometime trying to find a solution on this.

**Comment by HarelM** [comment]
Please provide a reproduction in jsbin/codepen that only uses maplibre-gl-js without any wrappers.

**Comment by HarelM** [comment]
Thanks for the info!
Yes, this does look like a bug.
I've looked at the code and haven't seen anything dramatic that would look like a bug so this needs deeper investigation.
If you would like to look into it that can be awesome.
The relevant class is mainly:
https://github.com/maplibre/maplibre-gl-js/blob/main/src/source/video_source.ts
`setCoordinates` is inherited from:
https://github.com/maplibre/maplibre-gl-js/blob/main/src/source/image_source.ts

And there's a usage of a texture to pass the data to the GPU.
My knowledge in this area is limited unfortunately...

**Comment by neodescis** [comment]
This bug [existed in Mapbox GL 1.x as well](https://github.com/mapbox/mapbox-gl-js/issues/10113), but was fixed with 2.x. It's been a while since I looked at it, but I did manage to work around it by disabling the fade animation.

**Comment by uditgogoi** [comment]
@neodescis I did tried in Mapbox latest versions, the issue still exist. In mapbox, the flashing doesn't shows up untill I do pause and play.

**Comment by neodescis** [comment]
Understood. Have you tried setting the layer's paint property `raster-fade-duration` to 0?

If we are to give this a proper fix, I think we'd need to nail down exactly when we want that fade effect to actually occur.

**Comment by uditgogoi** [comment]
@neodescis Yes I tried it and it didn't worked for me.

**Comment by uditgogoi** [comment]
@neodescis Yes I think you are right. I did tried adding the `raster-fade-duration` in a wrong location. For future reference, setting `raster-fade-duration` as 
```
layers: [
               {
                    id: "video",
                    type: "raster",
                    source: "video",
                    paint: {
                        'raster-fade-duration': 0
                    }
               }
            ]
```
seems to fix this issue.

Thanks a lot for this.

**Comment by HarelM** [comment]
It's probably worth mentioning this somewhere in the docs...

**Comment by HarelM** [comment]
It would be great if any of you could open a PR to update the docs so that other people in the future will know how to solve this issue...

**Comment by neodescis** [comment]
Where do you think is the appropriate place to document this? I see a very much related comment on ImageSource's updateImage function. VideoSource extends ImageSource, but then the actual property is part of RasterLayerSpecification.

I feel like it should be mentioned on VideoSource (and potentially ImageSource), as I don't know that anyone would know to look at RasterLayerSpecification when they're trying to keep a video from flashing.

**Comment by HarelM** [comment]
I would recommend adding it to the style spec source docs:
https://maplibre.org/maplibre-style-spec/sources/#video
And maybe in the top part of the `video_source.ts` comment.

cc: @birkskyum - can you check that the links to the style-spec docs from the code are correct? I see that some links to sources are not correct, for example in the video source comment in the `video_source.ts` file.

**Comment by neodescis** [comment]
There's not really much in the style-spec repo on how to get the docs up and running locally, and I haven't had much luck. solid-start lists out all of the routes, but then I see 404s when I browse to any of them.

**Comment by birkskyum** [comment]
@neodescis , 

I tried just now to clone the repo and run the docs. The steps I took were:
* It works for node 18, not for node 20
* npm install in root
* npm install in ./docs
* npm run dev in ./docs

**Comment by neodescis** [comment]
Thanks! I was using `npm start`. Not sure what the difference is, but it doesn't seem to serve up anything successfully.

**Comment by neodescis** [comment]
Documentation updates are done, so closing this as completed.
