### ISSUE TITLE
Control buttons don't reset to inactive style after click on touch devices

### ISSUE THREAD

**Issue by digitaltom** [maplibre/maplibre-gl-js#5284]
**maplibre-gl-js version**: 4.7.1 / 5.0

**browser**: Mobile Firefox, Mobile Chrome

### Steps to Trigger Behavior

 1. Click on any control button (like zoom-in, zoom-out)
 2. See the clicked control button still being active (highlighted)
 3. Control button state only gets reset after click on the map

The issue only happens on mobile browsers / touch devices. On desktop, the control button style resets correctly after click. 

### Link to Demonstration

Demo: https://jsbin.com/bomimibija/edit?html,output

### Expected Behavior

Control button highlight style should reset after click. 

### Actual Behavior

Control button highlight style stays active until click on map.
Video: 

https://github.com/user-attachments/assets/4ae6b618-f900-4099-bc97-152f6bdc67a6

**Comment by HarelM** [comment]
I tend to think this is related to the following issue:
- #4895

I believe this is related to a11y (accessibility) definitions of Firefox and mobile chrome.

**Comment by digitaltom** [comment]
Ok, I think I've found the issue: 
The maplibre css defines a hover effect on the ctrl buttons, which is discouraged on mobile, because mobile browsers set the hover state on click, but only reset it when clicking on some other element, not when dragging the map for example. 

CSS that causes this effect (https://github.com/maplibre/maplibre-gl-js/blob/22b95df91d3c69d98ddf9dbaee979bac62298016/src/css/maplibre-gl.css#L183): 

```
.maplibregl-ctrl button:not(:disabled):hover{
            background-color:rgb(0 0 0/5%)
```

[This jsbin](https://jsbin.com/zerugadume/1/edit?html,output) shows the a fixed behavior. 
I can propose a patch for this issue later.

**Comment by HarelM** [comment]
Can you link to an article about the discouraging you referenced above? 
Also, I think I still see the issue in the jsbin you linked...

**Comment by digitaltom** [comment]
I've corrected the jsbin link. I found for example [this article](https://itnext.io/finally-a-css-only-solution-to-hover-on-touchscreens-c498af39c31c) related to the issue. 

Recording of touch device behavior with the patch:  

https://github.com/user-attachments/assets/3484d1dc-80e4-4c93-9f6e-46db14d280bd

**Comment by HarelM** [comment]
Which jsbin has a fix that works on mobile? 
My chrome on Android is still showing the hover effect after click...

**Comment by digitaltom** [comment]
The jsbin https://jsbin.com/dedemareco/1/edit?html,output shows the behavior from the fixed video for me. 

I've also created: https://jsbin.com/wedujofugo/1/edit?html,css,output which has the full updated CSS from https://github.com/maplibre/maplibre-gl-js/pull/5285

**Comment by HarelM** [comment]
Using both links I still get this after clicking the + button, on Android (chrome), is this expected?
![Image](https://github.com/user-attachments/assets/4cf3e066-135a-44ef-ab17-0e6f401f78df)

**Comment by digitaltom** [comment]
I cannot explain this.... This is a video I just recorded of https://jsbin.com/wedujofugo/1/edit?html,css,output with Chrome 131 on Android 15: 

https://github.com/user-attachments/assets/0467cd12-a43d-428a-b277-334e21f19e7a

It works nicely there now.

**Comment by HarelM** [comment]
I have Android 14 but chrome 131 as well... Weird...

**Comment by digitaltom** [comment]
I've also tried on Safari/Ipad now, which shows the fixed behavior. Maybe you can try with Firefox/Chrome DevTools on Desktop, they can emulate touch device behavior too. For me, they also show it fixed.

**Comment by HarelM** [comment]
It's probably an improvement, so I'll merge it as is, you are welcome to continue try and reproduce what I'm seeing on your end to be able to solve this for more devices...

**Comment by digitaltom** [comment]
Thanks for your support!
